### PR TITLE
Make the axes convention for orientation configurable.

### PR DESCRIPTION
**Pull request by clalancette**
This allows the user to switch between NED (the default) and
ENU (more useful for ground robots).

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

@hidmic Opening this for visibility.  Feel free to do the work to first move the quaternion multiply into imu_vn_100.cpp; I'll then rebase this.

Also, please don't merge this until we discuss a little further, as we'll need to change some downstream code to configure this to ENU mode properly.

### CODE REVIEW

**Review by hidmic — COMMENTED** [review]
For the record, this LGTM

**Comment by clalancette** [comment]
All right, retargeted and rebased.  This should be good for merging now.

**Review by hidmic — APPROVED** [review]
LGTM!

**Comment by hidmic** [comment]
Going in!

**Pull request merged**
